languageCode = 'en-us'
title = 'Lake Hills Community Association'
theme = 'ananke'
subheadline = "Welcome to LHCA!"
paginate = 0

[params]
  featured_image = "/images/lhca-drone.jpg"
  custom_css = ["/css/custom.css"]


[development]
  baseURL = "http://localhost:1313/"

[production]
   baseURL = "https://docs.lakehillsca.org/"


[menu]
  [[menu.main]]
    identifier = "history"
    name = "History"
    url = "/history"
    weight = 1

  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq"
    weight = 2

